 export const Products =[{
    idPr:1,
    namePr:"Samsung Galaxy A72",
    imgPr:"https://m.media-amazon.com/images/I/71mae2Jl6JL._AC_SL1500_.jpg",
    pricePr:1599,
    detailesPr:["6.7 FHD+ sAMOLED+ HID" ," Quad Camera: 64MP (F1.8) + 12MP (F2.2) + 8MP (F2.4) + 5MP (F2.4)", " 8GB RAM and 128GB ROM (MicroSD Card up to 1TB)"],
    typePr:"Electronics",
    ratingPr:75,
    brandPr:"SAMSUNG",
    quantity:4
},
{
    idPr:2,
    namePr:"PlayStation 5 Digital Edition",
    imgPr:"https://m.media-amazon.com/images/I/51lVhQLZn+L._AC_SL1456_.jpg",
    pricePr:3299,
    detailesPr:["Lightning Speed - Harness the power of a custom CPU, GPU, and SSD with Integrated I/O that rewrite the rules of what a PlayStation console can do.","Stunning Games - Marvel at incredible graphics and experience new PS5 features.","Breathtaking Immersion - Discover a deeper gaming experience with support for haptic feedback, adaptive triggers, and 3D Audio technology."],
    typePr:"Video Games",
    ratingPr:90,
    brandPr:"Sony",
    quantity:2
},
{
    idPr:3,
    namePr:"PUMA Ignite Blaze Pro womens Golf Shoe",
    imgPr:"https://m.media-amazon.com/images/I/71WpOpUpDfL._AC_UL1500_.jpg",
    pricePr:472,
    detailesPr:["Full grain Atlantis leather","Hybrid bootie construction","Sole Material: Synthetic","Closure: Lace-Up","Ignite Foam","Grip Zone Traction","Tornado Cleat"],
    typePr:"Shoes",
    ratingPr:89,
    brandPr:"PUMA",
    quantity:10
},{
    idPr:4,
    namePr:"adidas E CAMO LIN TEE Mens T-SHIRTS",
    imgPr:"https://m.media-amazon.com/images/I/31vAjZAAH+S._AC_SY780_.jpg",
    pricePr:75,
    detailesPr:["Material: Cotton","Material Composition: 100% Cotton","Style: E CAMO LIN TEE","Style: E CAMO LIN TEE","Adidas Logo print"],
    typePr:"Fashion",
    ratingPr:45,
    brandPr:"Adidas",
    quantity:15
},
{
    idPr:5,
    namePr:"Flora 2 Pieces Coffee And Tea Vacuum Flask Set Matt Dark Smoky Gray",
    imgPr:"https://m.media-amazon.com/images/I/714Mm21mECL._AC_SL1500_.jpg",
    pricePr:156,
    detailesPr:["Thermos set 2 tablets to keep hot and cold liquids","Keeps temperature 12 hours and cold 24 hours","Made of high quality materials, the ability to pour water without removing the cover, comfortable handle and heat insulation","Keeps hot and cold drinks in temperature for a long time. Easy to use and wide stopper for easy pouring of water","Used at home, camping, trips and parties Ideal for keeping hot drinks for a long time environmentally friendly Easy to use"],
    typePr:"Kitchen",
    ratingPr:68,
    brandPr:"AlSaif",
    quantity:7
},
{
    idPr:6,
    namePr:"Artely Bis End Table",
    imgPr:"https://m.media-amazon.com/images/I/71SCPtK3F+L._AC_SL1500_.jpg",
    pricePr:78,
    detailesPr:["Versatility: use it as an end table, side table, sofa table, bedside table, it will valorize anywhere at your home","Functionality: perfect as a support to your cellphone and other daily things like cups and books","Open shelves: to show off your collections or favorite decorations and pictures, displaying your personality","Compact: simple yet elegant design, that matches well with any type of decoration and fits all corners","Quality: made from selected mdf and mdp, ensuring resistance and safety"],
    typePr:"Furniture",
    ratingPr:76,
    brandPr:"Artely",
    quantity:4
},
{
    idPr:7,
    namePr:"Vango Halo Pro Tent 200",
    imgPr:"https://m.media-amazon.com/images/I/81fTNPvEOjS._AC_SL1500_.jpg",
    pricePr:1294,
    detailesPr:["Material: Polyster","The Ground Sheet Is Waterproof","The Fabrics Are Fire Retardant","Capacity: 2 Person","Color: Grey"],
    typePr:"Camping & Hiking",
    ratingPr:61,
    brandPr:"Vango",
    quantity:7
},
{
    idPr:8,
    namePr:"Sonata NXT Water Resistant, White Dial Analog Watch with Calendar for Men",
    imgPr:"https://m.media-amazon.com/images/I/416xK2PlnhL._AC_SY1000_.jpg",
    pricePr:132,
    detailesPr:["Watch Shape : Round","Dial Case Diameter Size : 42 mm","Movement Type : Quartz"],
    typePr:"Fashion",
    ratingPr:49,
    brandPr:"Sonata",
    quantity:17
},
{
    idPr:9,
    namePr:"GUESS Washington Double Zip Crossbod",
    imgPr:"https://cdn.shopify.com/s/files/1/0217/8564/1060/products/sydney_luggage_guess_washington_double_zip_crossbody_brown_white_multi_logo_1_580x.jpg?v=1626140675",
    pricePr:240,
    detailesPr:["WASHINGTON DBL ZIP CROSSBODY","Closure: Zipper","Style: CROSSBODY"],
    typePr:"Fashion",
    ratingPr:87,
    brandPr:"GUESS",
    quantity:6
},
{
    idPr:10,
    namePr:"Wrap Tops",
    imgPr:"https://m.media-amazon.com/images/I/71PARSREhDL._SX385_.jpg",
    pricePr:46,
    detailesPr:["Top Style: Wrap Tops","Targeted Group: Women","Material: Viscose","Material Composition: 100% Viscose","Style: Asymmetrical Tops","Women Sleeve length: Full Sleeve"],
    typePr:"Fashion",
    ratingPr:95,
    brandPr:"Vero Moda",
    quantity:20
},
{
    idPr:11,
    namePr:"Big Slid Green F",
    imgPr:"https://m.media-amazon.com/images/I/411TQYpXs9L._AC_.jpg",
    pricePr:328,
    detailesPr:["Product weight: 15 KG","Targeted Group: Unisex","Age: 2 - 6 years","Outdoor Play Activities: Outdoor Activities & Games","Recommended Age: 2 - 6 years"],
    typePr:"Toys & Games",
    ratingPr:76,
    brandPr:"Best Toy",
    quantity:3
},
{
    idPr:12,
    namePr:"XFX Speedster QICK319 AMD Radeon RX 6700 XT Black Gaming Graphics Card with 12GB GDDR6 HDMI 3xDP, AMD RDNA 2 RX-67XTYPBDP",
    imgPr:"https://m.media-amazon.com/images/I/41lXeh15ptS._AC_.jpg",
    pricePr:6054,
    detailesPr:["Chipset: AMD RX 6700 XT","Memory: 12GB GDDR6 AMD RDNA 2 architecture elevates and unifies the gaming","Boost Clock: Up To 2622MHz","Cooling: XFX Speedster QICK319 Triple Fan"],
    typePr:"Electronics",
    ratingPr:"90",
    brandPr:"XFX",
    quantity:2
},
{
    idPr:13,
    namePr:"Power Bank Portable Charger 10000mAh with cable",
    imgPr:"https://m.media-amazon.com/images/I/315-H5D6hkL._AC_SL1000_.jpg",
    pricePr:79,
    detailesPr:["FAST CHARGE FOR MULTIPLE DEVICES – Power Bank rapidly charges the most power-hungry devices up to 100% in just an hour with no drop in voltage or current. Dual USB-A and USB-C ports allow users to charge two devices at once with a max output of 3 Amps individually. Great for Android and iOS devices!","EXCELLENT BATTERY – Charge and recharge your phone to 100% up to 3-5 times with the 10000mAh, large-capacity battery. Our power bank has an extended battery life and a long standby time, making it great to use in emergencies or on long, cross country road trips","COMPACT & SUPER LIGHTWEIGHT –our lightweight power bank fits easily into your pocket and is perfect for space-limited users. The matte textured finish makes it scratch resistant from bumps on hard surfaces, hides fingerprints and smudges, and provides a secure grip in your hands.","AUTOMATICALLY CHARGE & CERTIFIED SAFETY – Power Bank automatically delivers power upon connecting to a device – you do not need to press any buttons to power it up. It automatically powers off once the device is fully charged. While charging, it employs a muti-protection system to safeguard your devices","GREAT BACKUP ON-THE-GO PLAN – Our battery falls below the 100wh flight restriction and can be brought in your carry-on bag. Get one today and experience the difference that real quality makes!"],
    typePr:"Electronics",
    ratingPr:56,
    brandPr:"Value smash",
    quantity:13
},
{
    idPr:14,
    namePr:"New Apple iPhone 13 Pro Max",
    imgPr:"https://m.media-amazon.com/images/I/61IJBsHm97L._AC_SL1500_.jpg",
    pricePr:5199,
    detailesPr:["6.7-inch Super Retina XDR display with ProMotion for a faster, more responsive feel","Cinematic mode adds shallow depth of field and shifts focus automatically in your videos","Pro camera system with new 12MP Telephoto, Wide, and Ultra Wide cameras; LiDAR Scanner; 6x optical zoom range; macro photography; Photographic Styles, ProRes video, Smart HDR 4, Night mode, Apple ProRAW, 4K Dolby Vision HDR recording","12MP TrueDepth front camera with Night mode, 4K Dolby Vision HDR recording","A15 Bionic chip for lightning-fast performance"],
    typePr:"Electronics",
    ratingPr:94,
    brandPr:"Apple",
    quantity:5
},
{
    idPr:15,
    namePr:"ASUS VivoBook Flip 14 Thin and Light 2-in-1 Laptop",
    imgPr:"https://m.media-amazon.com/images/I/711-tnp94sL._AC_SL1500_.jpg",
    pricePr:1525,
    detailesPr:["Powerful & efficient Intel Celeron N4020 Processor (up to 2.8 GHz), 64GB eMMC storage, and 4GB DDR4 RAM","Secure with a fingerprint sensor integrated with Touchpad and a Trusted Platform Module (TPM) to store all your passwords","14 inch glossy screen in a 13 inch frame with NanoEdge Full HD and a touchscreen display with up to 178° viewing angle optimized for entertainment","Windows 10 Home in S Mode with 1-month Microsoft 365 trial for new customers","Lightweight and easy to take on-the-go at 1.5kg with a chiclet keyboard"],
    typePr:"Electronics",
    ratingPr:56,
    brandPr:"ASUS",
    quantity:25
},
{
    idPr:16,
    namePr:"Seiko Women's Dial Stainless Steel Band Watch",
    imgPr:"https://m.media-amazon.com/images/I/61t4W70SY4L._SY679_.jpg",
    pricePr:1243,
    detailesPr:["Japanese Quartz Movement","Case diameter: 27mm","Hardlex Crystal","Stainless Steel case with Stainless-Steel band","Water-resistant to 30 Meters / 100 Feet / 3 ATM"],
    typePr:"Fashion",
    ratingPr:46,
    brandPr:"Seiko",
    quantity:7
},
{
    idPr:17,
    namePr:"Samsung 27' Black Curve Monitor",
    imgPr:"https://m.media-amazon.com/images/I/71u8aohTxqL._AC_SL1500_.jpg",
    pricePr:1382,
    detailesPr:["UNMATCHED IMMERSION: Get your head in the game with Odyssey’s 1000R panel, which matches the curvature of the human eye for maximum immersion and minimal eye strain"],
    typePr:"Electronics",
    ratingPr:66,
    brandPr:"SAMSUNG",
    quantity:4
},
{
    idPr:18,
    namePr:"ALSAIF Cookware",
    imgPr:"https://m.media-amazon.com/images/I/61CqvXIXLgL._AC_SL1500_.jpg",
    pricePr:352,
    detailesPr:["Package weight in KGs: 11000 grams","Material: Stainless Steel","Type: Cookware Sets"],
    typePr:"Kitchen",
    ratingPr:89,
    brandPr:"AlSaif",
    quantity:13
},
{
    idPr:19,
    namePr:"Artely Matrix Desk With Niches",
    imgPr:"https://m.media-amazon.com/images/I/611h-juEnXL._AC_SL1500_.jpg",
    pricePr:167,
    detailesPr:["COMPLETE SOLUTION: combines the advantages of a desk with the ones of a bookcase, organizing and optimizing the space;","PERFECT- SIZE NICHES: ideal to put books, decorations and other materials of work or study;","TOP: space to put books, magazines and your notebook on;","HIGH QUALITY: made from selected MDF and MDP, reconstituted wood from reforested certified forests.","VERSATILE DESIGN: matches well with any type of decoration, whether in your bedroom or office;"],
    typePr:"Furniture",
    ratingPr:76,
    brandPr:"Artely",
    quantity:12
},
{
    idPr:20,
    namePr:"Sonata Blush It Up Water Resistant",
    imgPr:"https://m.media-amazon.com/images/I/413BC6ScWjL._AC_SY1000_.jpg",
    pricePr:187,
    detailesPr:["Watch Shape : Round","Dial Case Diameter Size : 32.90 mm","Movement Type : Quartz"],
    typePr:"Fashion",
    ratingPr:43,
    brandPr:"Sonata",
    quantity:23
},
{
    idPr:21,
    namePr:"PUMA Men's ESS Heather T-Shirt",
    imgPr:"https://m.media-amazon.com/images/I/41q-78GMi0L._AC_SY580_.jpg",
    pricePr:68,
    detailesPr:["No. 1 Logo rubber print Rib crew neck Regular fit Made with Cotton from Better Cotton Initiative Made with recycled polyester Made with OEKO-TEXStandard","Material: Main Material 1: 65% polyester Recycled, 35% cotton BCI, - single jersey - 160.00 g/m² - piece dyed - Chemical- Regular finishing Rib: 63% polyester Recycled, 33% cotton, 4% elastane - 1x1 rib - 290.00 g/m² - piece dyed - Chemical- Regular finishing","Care Instructions: Machine Wash","Sleeve Type: Short Sleeve","Closure: Pull On","Style: T-Shirt","Fit Type: Classic"],
    typePr:"Fashion",
    ratingPr:97,
    brandPr:"PUMA",
    quantity:3
},
{
    idPr:22,
    namePr:"adidas Energyfalcon mens Sneaker",
    imgPr:"https://i.frog.ink/0Go4mAJl/adidas-energy-falcon-running-shoes-slipper-ee9843-01_600.jpg?v=1566364227.85",
    pricePr:"289",
    detailesPr:["Mesh upper; Supportive Fitpanel overlay Durable Adiwear outsole; Supportive heel construction; Textile lining Cushioned Cloudfoam midsole; Enjoy the comfort and performance of OrthoLite sockliner","Closure: Lace-Up"],
    typePr:"Shoes",
    ratingPr:65,
    brandPr:"Adidas",
    quantity:12
},
{
    idPr:23,
    namePr:"Vango-Nitestar Sleeping Bag- 350- Surf Blue L",
    imgPr:"https://m.media-amazon.com/images/I/61y9WpihvkL._AC_SL1500_.jpg",
    pricePr:249,
    detailesPr:["210T Diamond Embossed Polyester - A Strong 100% Polyester With A Diamond Embossed Design","Off-Set Double Layer Construction - Off-Set Seams Prevent Cold Spots At The Stitching Lines","Two-Way Auto-Lock Zip - Seals In Warmth And Provides Adjustable Ventilation. Auto-Lock Prevents The Bag From Opening During The Night And Can Be Accessed From Inside The Bag"],
    typePr:"Camping & Hiking",
    ratingPr:93,
    brandPr:"Vango",
    quantity:2
},
{
    idPr:24,
    namePr:"GUESS Women's Katey Convertible Xbody Flap Shoulder Bag, Color: Orange",
    imgPr:"https://images-na.ssl-images-amazon.com/images/I/51XdZoU8J1L._SL500_._AC_SL500_.jpg",
    pricePr:291,
    detailesPr:["KATEY CONVERTIBLE XBODY FLAP","Pale Shiny Gold Hardware","Closure: Flap","Style: KATEY CONVERTIBLE XBODY FLAP","L: 24 W: 9 H: 16 cm","SHORT DROP:32 cm | LONG DROP: 58 cm","Leather - Synthetic"],
    typePr:"Fashion",
    ratingPr:23,
    brandPr:"GUESS",
    quantity:5
},
{
    idPr:25,
    namePr:"Vero Moda Women's BONNA 3/4 LACE Top",
    imgPr:"https://m.media-amazon.com/images/I/41vJDOCRxyL._AC_SY580_.jpg",
    pricePr:24,
    detailesPr:["Vero Moda branding","Item Type: Top","Material Composition: 100% Polyester","Care Instructions: Machine Wash","Style: Top","Style Number: 10237739","Target Group: Women's","100% Polyester","Machine wash - Cold (30° max)"],
    typePr:"Fashion",
    ratingPr:76,
    brandPr:"Vero modo",
    quantity:3
},
{
    idPr:26,
    namePr:"The famous Billiard For Children by Best Toy",
    imgPr:"https://m.media-amazon.com/images/I/51X8fHLYolL._AC_.jpg",
    pricePr:349,
    detailesPr:["Toy Category: Activity & Amusement","Targeted Group: Unisex"],
    typePr:"Toys & Games",
    ratingPr:75,
    brandPr:"Best Toy",
    quantity:1
},
{
    idPr:27,
    namePr:"XFX Radeon RX 580 GTS XXX Edition 1386MHz OC+, 8GB GDDR5, VR Ready, Dual BIOS, 3xDP HDMI DVI, AMD Graphics Card (RX-580P8DFD6)",
    imgPr:"https://m.media-amazon.com/images/I/81D46VNLb9L._AC_SL1500_.jpg",
    pricePr:2965,
    detailesPr:["The XFX RX 580 series graphics card feature the latest Polaris architecture which includes the 4th Gen GCN graphics cores, a brand new display engine, new multimedia cores, all on the revolutionary Next FinFET 14 process technology for enhanced performance and efficiency","Equipped with XFX Double Dissipation Cooling Technology for optimal cooling and performanc. Minimum power requirement is 500 watts. Memory Clock True:8.0GHz, Boost OC+:8.1GHz","Multiple Factory GPU Overclocked Settings - 1366MHz True Clock and 1386MHz OC+","AMD VR Ready Premium -Experience the new generation of compelling Virtual Reality content with the Radeon RX GTS graphics card paired with the leading VR headsets. The Radeon RX GTS graphics card coupled with AMD LiquidVR technology delivers a virtually stutter-free, low latency experience, essential for remarkable Virtual Reality environments"],
    typePr:"Electronics",
    ratingPr:63,
    brandPr:"XFX",
    quantity:1
},
{
    idPr:28,
    namePr:"Electric Scooter Ride-On Compatible White Motorbike for Kids",
    imgPr:"https://m.media-amazon.com/images/I/81UJK5u3bTL._AC_SL1500_.jpg",
    pricePr:550,
    detailesPr:["SAFETY FEATURES scooter: Added stabilizers making it safe and stable for little ones and provides extra safety","FOOT OPERATED ACCELERATOR: Operated by kids with their own foot operated pedal; reach speeds up","WORKING HEADLIGHTS AND ENGINE SOUNDS: Features a real key start function with music, horn, and engine sounds","RECHARGABLE BATTERY: Powered by a high power rechargeable battery for 1-2 hours run time","24/7 CUSTOMER SUPPORT TO HELP Your satisfaction is what drives us to provide the highest quality products. If you are not completely happy with your purchase, please contact us and we'll make it right!"],
    typePr:"Toys & Games",
    ratingPr:19,
    brandPr:"Value smash",
    quantity:4
},
{
    idPr:29,
    namePr:"Seiko Men's Black Dial Stainless Steel Band Watch",
    imgPr:"https://m.media-amazon.com/images/I/71knWGhV+eL._AC_SY879_.jpg",
    pricePr:456,
    detailesPr:["Japan 21 Jewels Automatic Movement (Calibre 7S26)","Stainless Steel Case and Band Push Button Release Clasp","Day/Date Display with Arabic Option, Hardlex Crystal for Durability, Luminous Hands, Silver Tone Hands"],
    typePr:"Fashion",
    ratingPr:65,
    brandPr:"Seiko",
    quantity:5
},
{
    idPr:30,
    namePr:"ASUS ROG Phone 5S 512GB 18GB RAM Global Version - Black",
    imgPr:"https://m.media-amazon.com/images/I/31Uv4dCnXPL._AC_.jpg",
    pricePr:4719,
    detailesPr:["6.78 144Hz AMOLED Display","Qualcomm Snapdragon 888+","5G Mobile Platform","Memory : 18GB","Storage : 512GB"],
    typePr:"Electronics",
    ratingPr:67,
    brandPr:"ASUS",
    quantity:2
},
{
    idPr:31,
    namePr:"2021 Apple MacBook Pro (16-inch, Apple M1 Pro chip with 10‑core CPU and 16‑core GPU, 16GB RAM, 1TB SSD) - Space Grey",
    imgPr:"https://m.media-amazon.com/images/I/61s6UawAo5L._AC_SL1500_.jpg",
    pricePr:12739,
    detailesPr:["Apple M1 Pro or M1 Max chip for a massive leap in CPU, GPU and machine learning performance","Up to 10-core CPU delivers up to 2x faster performance to fly through pro workflows quicker than ever","Up to 32-core GPU with up to 4x faster performance for graphics-intensive apps and games","16-core Neural Engine for up to 5x faster machine learning performance","Longer battery life, up to 21 hours","Up to 64GB of unified memory so everything you do is fast and fluid","Up to 8TB of superfast SSD storage launches apps and opens files in an instant"],
    typePr:"Electronics",
    ratingPr:87,
    brandPr:"Apple",
    quantity:1
},
{
    idPr:32,
    namePr:"PlayStation 5 DualSense Wireless Controller (KSA Version) - Midnight Black",
    imgPr:"https://m.media-amazon.com/images/I/61CdkDnFw6S._AC_SL1475_.jpg",
    pricePr:263,
    detailesPr:["Discover a deeper, highly immersive gaming experience with the innovative new PS5 controller, featuring haptic feedback and dynamic trigger effects","The DualSense wireless controller also includes a built-in microphone and create button, all integrated into an iconic, comfortable design","Feel physically responsive feedback to your in-game actions with dual actuators which replace traditional rumble motors. In your hands, these dynamic vibrations can simulate the feeling of everything from environments to the recoil of different weapons","Experience varying levels of force and tension as you interact with your in-game gear and environments. From pulling back an increasingly tight bowstring to hitting the brakes on a speeding car, feel physically connected to your on-screen actions."],
    typePr:"Video Games",
    ratingPr:56,
    brandPr:"Sony",
    quantity:5
},
{
    idPr:33,
    namePr:"Puma Unisex Originals Backpacks",
    imgPr:"https://images-eu.ssl-images-amazon.com/images/I/81LF9Te-PDL._AC_SR462,693_.jpg",
    pricePr:219,
    detailesPr:["Two-way zip opening into main compartment with interior elastic lining compartment","Front compartment with zip opening and large PUMA print","Closure: Zipper","Style: Shoe Care & Accessories","Internal laptop sleeve","Ring-designed zippers with engraved brand.","Padded shoulder straps and back panel provide comfy carrying.","Dimensions: 42.5 cm (H) x 29 cm (W)"],
    typePr:"Fashion",
    ratingPr:63,
    brandPr:"PUMA",
    quantity:7
},
{
    idPr:34,
    namePr:"adidas BB CA 3S 4AT AR Unisex HEADWEAR",
    imgPr:"https://m.media-amazon.com/images/I/81FUoJapJXL._SL1500_.jpg",
    pricePr:67,
    detailesPr:["padded sweatband provides soft fit and absorbs moisture","for performance look and best visibility","Style: baseball","A medium curved crown and visor stand for a classical baseball cap which is always on trend"],
    typePr:"Fashion",
    ratingPr:70,
    brandPr:"Adidas",
    quantity:9
},
{
    idPr:35,
    namePr:"SAMSUNG GALAXY FIT 2 FITNESS TRACKER RED",
    imgPr:"https://m.media-amazon.com/images/I/61NlWXC0ySL._AC_SL1500_.jpg",
    pricePr:199,
    detailesPr:["Red","Make every move count","Alert's you on important events or Activities","Fitness Companion","Proactive Health Monitoring"],
    typePr:"Electronics",
    ratingPr:83,
    brandPr:"SAMSUNG",
    quantity:6
},
{
    idPr:36,
    namePr:"Alsaif Healthy Fryer Without oil",
    imgPr:"https://m.media-amazon.com/images/I/614+1jvPVQL._AC_SL1500_.jpg",
    pricePr:443,
    detailesPr:["Package weight in KGs: 8300 grams","Type: Air Fryers","Capacity: 9 liters"],
    typePr:"Kitchen",
    ratingPr:97,
    brandPr:"AlSaif",
    quantity:2
},
{
    idPr:37,
    namePr:"Sonata RPM Water Resistant, Blue Dial Analog Watch with Calendar for Men",
    imgPr:"https://m.media-amazon.com/images/I/51MOR8GmefL._AC_SY1000_.jpg",
    pricePr:118,
    detailesPr:["Watch Shape : Round","Dial Case Diameter Size : 40.5 mm","Movement Type : Quartz"],
    typePr:"Fashion",
    ratingPr:45,
    brandPr:"Sonata",
    quantity:9
},
{
    idPr:38,
    namePr:"Artely Wall Panel for 42 in ch TV, White - H 89.5 cm X W 120 cm X D 28 cm",
    imgPr:"https://m.media-amazon.com/images/I/61nUWgi+lvL._AC_SL1500_.jpg",
    pricePr:143,
    detailesPr:["UTILITY: modern product, perfect to put your TV on, which can safely be up to 42 inches","EASINESS: comes with a secure TV support and hardware to attach the tv, so you don't need to buy anything else","PRACTICAL SHELVES: ideal support to TV receptor, video games, DVD player, clock and your favorite decorations","VERSATILITY: intended to combine with the most varied environments, this wall panel of multipurpose and simple design will fit perfectly anywhere at your home","QUALITY: made from selected MDF and MDP and finished in textured painting, what provides resistance to attrition and moisture",],
    typePr:"Furniture",
    ratingPr:43,
    brandPr:"Artely",
    quantity:4
},
{
    idPr:39,
    namePr:"Vango Trekking Rucksacks, Black , RUNTMB B05R1I",
    imgPr:"https://m.media-amazon.com/images/I/31BEVbExleL._AC_.jpg",
    pricePr:672,
    detailesPr:["Self Adjust (SA) back system - Based on the patented A3 system. SA is robust, highly tested and will fit just about all back lengths","Shaped adjustable harness - Provides optimum fit and comfort","Excel 600D Polyester - 600 Denier yarn, back coated with PU for a multi-purpose, robust fabric","Daisy chain allows accessory attachment","Top lid with zip pocket - Provides easy access and safe storage for small items","Dual side compression straps - Stabilise rucksack contents","Additional zip pocket under lid - Safe storage for small items","Expansion side zip pockets - Slim profile pack with extra storage capacity when required","Water resistant zipped compartment - Designed to accommodate OS map","Pro-weave side pockets - Constructed from highly durable, yet extremely flexible material. Pockets sit flush with the pack when empty. Allows easy access to essential items"],
    typePr:"Camping & Hiking",
    ratingPr:38,
    brandPr:"Vango",
    quantity:5
},
{
    idPr:40,
    namePr:"Guess Tyren Status Satchel Bag For Women",
    imgPr:"https://m.media-amazon.com/images/I/91SM9-xxAIL._AC_SL1500_.jpg",
    pricePr:625,
    detailesPr:["Style Name: Tyren Status Satchel","Category: Women Handbags","Material: 100% PU","Care Instructions: Dry Clean Only","Closure: Zipper","Style: TYREN STATUS SATCHEL","Type: Status Satchel"],
    typePr:"Fashion",
    ratingPr:64,
    brandPr:"GUESS",
    quantity:4
},
{
    idPr:41,
    namePr:"Vero Moda Women's HENNY LACE LONG-SLEEVE Top",
    imgPr:"https://m.media-amazon.com/images/I/41TEoDIsNIS._AC_.jpg",
    pricePr:46,
    detailesPr:["Item Type: Top","Material Composition: 75% Cotton25% Nylon","Care Instructions: Machine Wash","Sleeve Type: Long Sleeve","Style: Top"],
    typePr:"Fashion",
    ratingPr:58,
    brandPr:"Vero Moda",
    quantity:4
},
{
    idPr:42,
    namePr:"Best Toy Playhouse With Slide For Kids",
    imgPr:"https://m.media-amazon.com/images/I/813coDc7oFL._AC_SL1500_.jpg",
    pricePr:1004,
    detailesPr:["Product weight: 15 to 20 KG","Targeted Group: Unisex","Age: 3 years","Outdoor Play Activities: Playhouses & Climbers","Recommended Age: 3 - 6 Years"],
    typePr:"Toys & Games",
    ratingPr:75,
    brandPr:"Best Toy",
    quantity:5
},
{
    idPr:43,
    namePr:"Value Smash wireless Headphones",
    imgPr:"https://m.media-amazon.com/images/I/71Da4YPSlmL._AC_SL1500_.jpg",
    pricePr:68,
    detailesPr:["[Bluetooth] Have fun with good sound quality, adopt APTX professional audio compression codec technology, reduce delay, transmit faster, lower energy consumption, and retain beautiful sound! And supports HSP HFP, A2DP, and AVRCP","[Powerful speaker] powerful speaker, the sound quality is pure and true to restore various music rhythms, the high, middle and low three frequencies are delicately connected, and the overall sound is warm and solid","[Comfortable to wear] comfortable headwear, no pressure to wear, the entire headwear is wrapped in soft material, matched with large ear shells, compressive and breathable, and comfortable to wear","[Long battery life] The long battery life is sturdy and durable. It can be charged for two hours. It is no longer troublesome for power, and it can be used as a cable without electricity","[After-sales service] Thank you for using our products. If you have any questions after receiving our products, please contact us via email as soon as possible. We will use our services to provide you with the most intimate experience"],
    typePr:"Electronics",
    ratingPr:83,
    brandPr:"Value Smash",
    quantity:2
},
{
    idPr:44,
    namePr:"Apple AirPods with Charging Case",
    imgPr:"https://m.media-amazon.com/images/I/71NLN1HgFkL._AC_SL1500_.jpg",
    pricePr:499,
    detailesPr:["Universal fit that’s comfortable all day","Automatically on, automatically connected","Easy setup for all your Apple devices","Quick access to Siri by saying “Hey Siri”","Seamless switching between devices"],
    typePr:"Electronics",
    ratingPr:61,
    brandPr:"Apple",
    quantity:13
},
{
    idPr:45,
    namePr:"Seiko Men's SNK809 Seiko 5 Automatic Stainless Steel Watch with Black Canvas Strap",
    imgPr:"https://m.media-amazon.com/images/I/41K09syALgL._AC_SY1000_.jpg",
    pricePr:414,
    detailesPr:["To the start the watch initially, swing from side to side in a horizontal arc about 30 seconds","37 mm stainless steel case and Hardlex mineral dial window and Precise 21-jewel automatic movement with analog display","Features include luminosity, sweeping second hand, canvas band, and a date window that can be formatted in English or Spanish"],
    typePr:"Fashion",
    ratingPr:89,
    brandPr:"Seiko",
    quantity:12
},
{
    idPr:46,
    namePr:"Seiko Men's 'RECRAFT SERIES' Automatic Stainless Steel and Leather Casual Watch",
    imgPr:"https://m.media-amazon.com/images/I/41U4n5zWFDL._AC_SY1000_.jpg",
    pricePr:868,
    detailesPr:["Self-winding automatic","Power reserve: approximately 41 hours","Automatic-self-wind Movement","Case Diameter: 39.5mm","Water resistant to 50m (165ft: in general, suitable for short periods of recreational swimming, but not diving or snorkeling"],
    typePr:"Fashion",
    ratingPr:54,
    brandPr:"Seiko",
    quantity:14
},
{
    idPr:47,
    namePr:"ASUS ROG Kunai 3 Gamepad",
    imgPr:"https://m.media-amazon.com/images/I/81ZDIawCdbL._AC_SL1500_.jpg",
    pricePr:533,
    detailesPr:["Game-console gamepad can be utilized in handheld mode, mobility mode and all-in-one","Handheld mode offers a zero latency USB 2.0 Type-C connection","Ergonomic design and excellent key feelings","Up to 6 hrs in wireless mode","USB Type C 2.0 and Bluetooth connection"],
    typePr:"Electronics",
    ratingPr:33,
    brandPr:"ASUS",
    quantity:3
},
{
    idPr:48,
    namePr:"Artely Wooden Tv Table, Black",
    imgPr:"https://m.media-amazon.com/images/I/61MeE1Q+PYL._AC_SL1500_.jpg",
    pricePr:330,
    detailesPr:["Product tested to safely support TV up to 60 inches","Reversible doors on versions Cinnamon, Pine and White. The doors are painted one side of each colour, and you choose your favorite during assembly","Casters that facilitate movements","The finishing is made in textured UV painting, and the Off White is made in high gloss UV painting, both of long durability and easy cleaning."],
    typePr:"Furniture",
    ratingPr:33,
    brandPr:"Artely",
    quantity:2
},
{
    idPr:49,
    namePr:"6 Liters Stand Mixer 1200W, 6 Speeds With Stainless Steel Bowl, Silver Color, With Dough Hook Wire Whip & Beater ALSAIF-ELEC",
    imgPr:"https://m.media-amazon.com/images/I/514LG6u53QL._AC_SL1000_.jpg",
    pricePr:399,
    detailesPr:["Power : 1200watts , 220-240V","Capacity : 6 Liters , With Stainless Steel Bowl","PRIME Stand Mixer From ALSAIF Makes Your Life Simpler In The Kitchen","3 Different Attached Accessories ( Dough Hook Wire Whip & Beater )","2 Years Warranty"],
    typePr:"Kitchen",
    ratingPr:86,
    brandPr:"AlSaif",
    quantity:9
},
{
    idPr:50,
    namePr:"KTT Extra Large Tent 12 Person",
    imgPr:"https://m.media-amazon.com/images/I/81rRb6OUqkS._AC_SL1500_.jpg",
    pricePr:1694,
    detailesPr:["Large space:Inside dimension14.1ft length*10ft width*6.58ft height, fit 4 full air mattresses(6.7ft*5ft/200cm*150cm),can accommodate 10 12 person,3 doors with mesh,3 Windows with mesh,divided into two rooms by separation curtain.","Materials: double layer waterproof polyester, High density mesh, The tent floor material is super thick with PE coated polyester.","Function: For outdoor leisure use.","Unique design: straight wall design, interior space is larger and more comfortable. If the door curtain supports by two poles, it becomes a sunshade canopy. The top of the tent is high density mesh, very breathable, we can enjoy the beautiful scenery of the sky when lying inside.","KTT Camping tent not only focus on the quality, but also pay attention to its practicality. We add 2 poles for the door curtain, it can immediately become an awning tent, family members can take a rest inside, also can play outside under the awning. Although it raises the cost, it brings you pleasure..Warning (Precautions):1).Tents should not be placed on the ground with sharp objects (such as sharp stones, branches, grass roots ground etc.). 2).It is suggested to lay a mat first and then place the tent on it, which can protect the bottom of the tent. 4).Three glass fiber rods on the roof, the short one is under the two long ones..4).Install the support rod and nail it on the ground immediately. 5).Set up the rainfly and nail it on the ground with ropes and stakes immediately. 6).Do not use it in the bad weather such as strong wind, heavy rain and heavy snow. 7). 3 season tent 8).No smoking & no open fires in tent."],
    typePr:"Camping & Hiking",
    ratingPr:47,
    brandPr:"Vango",
    quantity:3
},
{
    idPr:51,
    namePr:"GUESS Men's FRONT LOGO T-Shirt",
    imgPr:"https://m.media-amazon.com/images/I/41tggl95f1L._AC_SY1000_.jpg",
    pricePr:100,
    detailesPr:["Crew Neckline","Material: 95%COTTON 5%ELASTANE","Care Instructions: Machine Wash","Sleeve Type: Short Sleeve","Closure: Buckle","Style: GJM GRAPHIC TEE","Fit Type: Classic"],
    typePr:"Fashion",
    ratingPr:74,
    brandPr:"GUESS",
    quantity:6
},
{
    idPr:52,
    namePr:"SAMSUNG Galaxy Tab S7",
    imgPr:"https://m.media-amazon.com/images/I/91QN3eSk9lS._AC_SL1500_.jpg",
    pricePr:2002,
    detailesPr:["Display: With the 12.4” display, you’re in for a bigger, brighter, and smoother cinematic experience. It's complemented with sound by AKG.","Upgraded S Pen: Write like never before with the new, upgraded S Pen experience. It comes packed with the versatility of Bluetooth, gesture control, and so much more, giving you an immersive tablet experience.","10,090mAh battery with up to 45W Super Fast Charging: All the fuel in minutes shareable and available wirelessly. It doesn't stop there they are intelligent, analysing your usage patterns to save more power, giving you more charge.","Let’s talk performance: With a fast processor, experience top-notch multi-tasking performance, gaming, pushing the limits of your work and play with minimal lag.","High-speed connectivity: With LTE, you get to do more of what you love. Enjoy your moments and share it too at super-fast speeds."],
    typePr:"Electronics",
    ratingPr:53,
    brandPr:"SAMSUNG",
    quantity:18
},
{
    idPr:53,
    namePr:"Sony 65 Inch TV Ultra HD HDR Bravia Core™ Smart Google TV",
    imgPr:"https://m.media-amazon.com/images/I/71sIJMpGuDS._AC_SL1200_.jpg",
    pricePr:4449,
    detailesPr:["Sony 65 Inch Android 4K HDR Smart LED TV"],
    typePr:"Electronics",
    ratingPr:86,
    brandPr:"Sony",
    quantity:2
},
{
    idPr:54,
    namePr:"PUMA child Big Kid's Lunch",
    imgPr:"https://m.media-amazon.com/images/I/51KyqHGCcZL._AC_SY580_.jpg",
    pricePr:145,
    detailesPr:["Pockets: 2 exterior; includes additional bag","Material: 100% Polyester","Care Instructions: Hand Wash Only","Closure: Zipper","Style: Evercat Backpack & Lunch Kit Combo"],
    typePr:"Fashion",
    ratingPr:78,
    brandPr:"PUMA",
    quantity:16
},
{
    idPr:55,
    namePr:"Apple Watch Series 6 (GPS + Cellular, 44mm)",
    imgPr:"https://m.media-amazon.com/images/I/91WXvuRCnvS._AC_SL1500_.jpg",
    pricePr:2699,
    detailesPr:["GPS + Cellular model lets you call, text, and get directions without your phone","Measure your blood oxygen with an all-new sensor and app","Check your heart rhythm with the ECG app","The Always-On Retina display is 2.5x brighter outdoors when your wrist is down","S6 SiP is up to 20% faster than Series 5"],
    typePr:"Electronics",
    ratingPr:19,
    brandPr:"Apple",
    quantity:3
},
{
    idPr:56,
    namePr:"Artely Cooler Desk With Drawer",
    imgPr:"https://m.media-amazon.com/images/I/61NV6Fhr8rL._AC_SL1000_.jpg",
    pricePr:153,
    detailesPr:["Verstaility: combines with the most varied styles, will be beautiful in offices and bedrooms of childs, teenagers and adults","Compact size: ideal to optimize the small spaces, easy to fit any corner","Drawer: storage daily materials of your work or study; opens with metal sliders to soft movements","Modern design: simple clean-cut lines harmonize and give balance to the room","Quality: made from selected MDF and MDP, reconstituted wood from reforested certified forests"],
    typePr:"Furniture",
    ratingPr:78,
    brandPr:"Artely",
    quantity:7
},
{
    idPr:57,
    namePr:"adidas Men's HOODED TRACK TOP",
    imgPr:"https://ean-images.booztcdn.com/adidas/1300x1700/g/adigk9032_cblackwhite.jpg",
    pricePr:214,
    detailesPr:["Full zip with drawcord-adjustable hood","53% cotton, 36% recycled polyester, 11% viscose French terry","Material: 53% Cotton/36% rec polyester/11% Viscose","Care Instructions: Machine Wash","Closure: Zipper","3 Stripes on both sleeves"],
    typePr:"Fashion",
    ratingPr:34,
    brandPr:"Adidas",
    quantity:2
},
{
    idPr:58,
    namePr:"Electric Pressure Cooker",
    imgPr:"https://m.media-amazon.com/images/I/71pC2+hS-ML._AC_SL1500_.jpg",
    pricePr:337,
    detailesPr:["Alsaif-Elec Pressure Cooker Stainless Steel Multicolour.","Electric pressure cooker, the outside of stainless steel with a non-stick coating, makes cleaning very easy.","Multiple uses, high quality and safe use thanks to features such as smart cover closing with automatic pressure control.","It includes preset timing for cooking soups, meats, poultry, and many other delicacies. The automatic pressure control and lid closing keep the food fresh and tender and preserve its flavor.","27 hour timing and automatic timer from 1 to 99 minutes make this device ideal for families and female employees to use."],
    typePr:"Kitchen",
    ratingPr:70,
    brandPr:"AlSaif",
    quantity:3
},
{
    idPr:59,
    namePr:"Sonata Volt+ Water Resistant, Black Dial Analog Watch For Men",
    imgPr:"https://m.media-amazon.com/images/I/41aX2viQi6L._AC_SY1000_.jpg",
    pricePr:95,
    detailesPr:["Watch Shape : Round","Dial Case Diameter Size : 45 mm","Movement Type : Quartz"],
    typePr:"Fashion",
    ratingPr:24,
    brandPr:"Sonata",
    quantity:5
},
{
    idPr:60,
    namePr:"Guess Women's Sunglasses Butterfly",
    imgPr:"https://m.media-amazon.com/images/I/315NFDIA2nL._AC_SY580_.jpg",
    pricePr:41,
    detailesPr:["Look fashionable, stylish, and flawless while also protecting your eyes from the harmful rays of sun with these fabulous sunglasses from Guess.","Comes with a cleaning cloth and Protective case","Provides 100% UV protection"],
    typePr:"Fashion",
    ratingPr:65,
    brandPr:"GUESS",
    quantity:5
},
{
    idPr:61,
    namePr:"Samsung Galaxy Watch",
    imgPr:"https://m.media-amazon.com/images/I/61TwhmWO6YL._AC_SL1500_.jpg",
    pricePr:1599,
    detailesPr:["Body Composition Analysis: Know your body, own your body. With the built-in BioActive Sensor, measure your body's fat percentage, skeletal muscle, body water and more. Level up your fitness game straight from your wrist.","Health comes first: Get Blood Pressure and ECG readings, all from a twist of your wrist. It's a watch that's watching out for you.","Sleep monitoring: Call the night off with the most holistic sleep analysis. Make it a good night, every day.","Fitness: Go beyond listening to your body, know it. It's fitness within arm's reach.","Compatibility: Your Galaxy Watch4 Classic comes with Wear OS powered by Samsung, helping you connect and play along well with Galaxy devices. Experience the best, right from your wrist."],
    typePr:"Electronics",
    ratingPr:52,
    brandPr:"SAMSUNG",
    quantity:3
},
{
    idPr:62,
    namePr:"PUMA Axelion mens Running Shoe",
    imgPr:"https://m.media-amazon.com/images/I/81lS3BdJLmS._AC_UX395_.jpg",
    pricePr:286,
    detailesPr:["Laces extend further down the sides of your foot for a supportive fit.","TPU Shank provides support and motion control through the heel and midfoot.","Sole Material: Rubber","Closure: Lace-Up","Heel Type: No Heel","Rubber outsole for durability and optimal traction."],
    typePr:"Shoes",
    ratingPr:57,
    brandPr:"PUMA",
    quantity:6
},
{
    idPr:63,
    namePr:"Apple AirPods Max - Space Grey",
    imgPr:"https://m.media-amazon.com/images/I/81yI9T5VdwL._AC_SL1500_.jpg",
    pricePr:1999,
    detailesPr:["Apple-designed dynamic driver provides high-fidelity audio","Active Noise Cancellation blocks outside noise, so you can immerse yourself in music","Transparency mode for hearing and interacting with the world around you","Spatial audio with dynamic head tracking provides theater-like sound that surrounds you","Computational audio combines custom acoustic design with the Apple H1 chip and software for breakthrough listening experiences"],
    typePr:"Electronics",
    ratingPr:38,
    brandPr:"Apple",
    quantity:5
},
{
    idPr:64,
    namePr:"Sony FDR AX700 4K HDR Camcorder with Exmor RS CMOS image sensor, Black",
    imgPr:"https://m.media-amazon.com/images/I/71UUI2vTyEL._AC_SL1500_.jpg",
    pricePr:751,
    detailesPr:["4K Hdr Hlg Recording","29.0Mm Wide Angle Zeiss Vario Sonnar T Lens","Up To 273 Point Phase Detection Af","Versatile Manual Settings","Up To 960Ntsc/1000Palfps Super Slow Motion","Viewfinder Type : Oled, Digital Zoom : 192.0 Multiplier X. image stabilization : Optical","max focal length : 348.0 millimeters","optical sensor resolution : 14.2 megapixels","optical zoom : 12.0 multiplier x"],
    typePr:"Electronics",
    ratingPr:19,
    brandPr:"Sony",
    quantity:2
},
{
    idPr:65,
    namePr:"adidas Men's M BL FT SWT SWEATSHIRT",
    imgPr:"https://sgfm.elcorteingles.es/SGFM/dctm/MEDIA03/202011/27/00132417811992____4__640x640.jpg",
    pricePr:181,
    detailesPr:["Ribbed cuffs and hem","Material: 53% cotton, 36% recycled polyester, 11% viscose French terry","Care Instructions: Machine Wash","Sleeve Type: Short Sleeve","Closure: Pull On","Style: Casual"],
    typePr:"Fashion",
    ratingPr:72,
    brandPr:"Adidas",
    quantity:8
},
{
    idPr:66,
    namePr:"Artely Wooden Coffee Table, Pine Brown",
    imgPr:"https://m.media-amazon.com/images/I/91r3dG2JfXL._AC_SL1500_.jpg",
    pricePr:236,
    detailesPr:["Comfort: this product is a perfect support for your stuff when you're enjoying your moments with your family on your sofa","Mirror details: pieces of mirror make the product very elegant, charming and sophisticated","Utility: ample top and bottom to put magazines, books, picture frames, decorations, daily things and many other things","Style: unique design, provided by the mirrors, that will make your home much more charming and modern","Durability: robust and long lasting product, finished in textured painting, what provides resistance to attrition and moisture"],
    typePr:"Furniture",
    ratingPr:45,
    brandPr:"Artely",
    quantity:2
},
{
    idPr:67,
    namePr:"Vango Chair Corona Recliner 2 Chair",
    imgPr:"https://m.media-amazon.com/images/I/71AcOeXGt9L._AC_SL1500_.jpg",
    pricePr:325,
    detailesPr:["Strong And Reliable Steel Frame. Arm Supports Covered With Fabric For Comfort","Maintains Temperature Of Hot And Cold Drinks For Longer","Easy Storage And Transport","Extra Padding On The Seat And Backrest","It Also Offers 3 Seating Positions"],
    typePr:"Camping & Hiking",
    ratingPr:5,
    brandPr:"Vango",
    quantity:1
},
{
    idPr:68,
    namePr:"SEIKO Men's Kinetic Watch, Analog Display and Leather Strap",
    imgPr:"https://images-na.ssl-images-amazon.com/images/I/41j4jOfr4RL._SL500_._AC_SL500_.jpg",
    pricePr:976,
    detailesPr:["Black Leather strap","Automatic movement","Case diameter: 42mm"],
    typePr:"Fashion",
    ratingPr:55,
    brandPr:"Seiko",
    quantity:5
},
{
    idPr:69,
    namePr:"Apple iMac (27-inch, 3.8GHz 8-core 10th-generation Intel Core i7 processor, 8GB RAM, 512GB SSD)",
    imgPr:"https://m.media-amazon.com/images/I/612zdML6eES._AC_SL1254_.jpg",
    pricePr:699,
    detailesPr:["27-inch (diagonal) 5120-by-2880 Retina 5K display","3.8GHz 8-core 10th-generation Intel Core i7","AMD Radeon Pro 5500 XT graphics","Ultrafast SSD storage","Two Thunderbolt 3 (USB-C) ports"],
    typePr:"Electronics",
    ratingPr:88,
    brandPr:"Apple",
    quantity:4
},
{
    idPr:70,
    namePr:"Vero Moda Aware Womens Vmgenova Wl Top Ga Long Sleeve Fashion Blouses",
    imgPr:"https://m.media-amazon.com/images/I/81V35aTG1YL._SL1500_.jpg",
    pricePr:46,
    detailesPr:["Material Composition: 100% Cotton","Top Style: Blouses","Material: Cotton","Material Composition: 100% Cotton","Care Instructions: Machine Wash","Style: Blouses","Neck Style: Round Neck"],
    typePr:"Fashion",
    ratingPr:17,
    brandPr:"Vero Moda",
    quantity:6
},
{
    idPr:71,
    namePr:"Value Smash High-quality Curt Angle action figures toys Battle game kids toys ",
    imgPr:"https://m.media-amazon.com/images/I/71ybHCNLhvL._AC_SL1500_.jpg",
    pricePr:69,
    detailesPr:["Different characters 16-18cm High occupation wrestling gladiators’ wrestler action figure Toys","Action figure features articulation, True FX enhanced facial detailing for life-like authenticity and ring gear.","Pretending to play & Great as Cake Topper -- Kids can imagine themselves as a wrestling warrior using this toy to help their imagination. It also great as cake topper for wrestling fans.","A fun game for children from exciting and exciting games Help to promote the spirit","Great for the Price -- You could get a lot of pieces little wrestling figure, the material is plastic, it is durable and nontoxic"],
    typePr:"Toys & Games",
    ratingPr:52,
    brandPr:"Value Smash",
    quantity:4
},
{
    idPr:72,
    namePr:"ASUS ROG Strix Flare (Cherry MX Red) Aura Sync RGB Mechanical Gaming Keyboard",
    imgPr:"https://m.media-amazon.com/images/I/91DbiglR1qL._AC_SL1500_.jpg",
    pricePr:617,
    detailesPr:["Cherry MX RGB switches for faster response times and enhanced gaming performance","100 percent anti ghosting, full key rollover, and onboard memory for on the fly macro recording","Customizable logo badge for adding your own flare to your gaming station","ASUS Aura Sync RGB lighting features a nearly endless spectrum of colors with the ability to synchronize effects across an ever expanding ecosystem of AURA Sync enabled products","Integrated media controls keep your hands on the keyboard during intense gaming sessions"],
    typePr:"Electronics",
    ratingPr:13,
    brandPr:"ASUS",
    quantity:6
},
{
    idPr:73,
    namePr:"Sony PS4 Dualshock 4 Controller, Green Camouflage (Official Version)",
    imgPr:"https://m.media-amazon.com/images/I/71vvEvjS9AL._AC_SL1500_.jpg",
    pricePr:299,
    detailesPr:["Ergonomic design: Get to grips with an elegant, super comfortable design, while highly responsive analog sticks and buttons mean greater precision during gameplay","Share button: Use the share button to upload your gameplay videos and pictures on social networks; stream live gameplay to twitch, YouTube and Dailymotion or edit your recorded gameplay videos and share them on Facebook and Twitter; you can also invite online friends to play your games with you, even if they don’t own them with share play","Touch pad: Guide, gesture and draw with the responsive touch pad now restyled so you can see your light bar colour from above as you play","Light bar : The integrated light bar can emit various colours to personalise your experience and add a new dimension to games; it also helps the PlayStationCamera track your controller position allowing you to interact with your games; it also helps the PlayStationCamera track your controller position allowing you to interact with your virtual surroundings while using PlayStationVR","Built-in speaker and stereo headset jack: Enjoy extra sound effects straight from the controller and chat with online friends via a headset, such as the stereo headset included with the PS4 system","Vibration feedback: Feel even more deeply engaged with the action as the controller shudders and shakes in your hands, thanks to intuitive vibration motors","Remote play: Stream your PS4 games to a WindowsPC or Mac so you can keep on playing even when you’re away from the TV; the DUALSHOCK4 USB wireless adaptor makes remote play on your computer even better, allowing you to play wirelessly","Customised control: Prepare your DUALSHOCK4 wireless controller just the way you like it set the speaker volume, disable vibrations, plus adjust the light bar brightness to conserve battery life when not required; you can also choose to communicate data via Bluetooth or by using a USB cable connected to your PS4"],
    typePr:"Video Games",
    ratingPr:81,
    brandPr:"Sony",
    quantity:1
},
{
    idPr:74,
    namePr:"Samsung Galaxy Note20 Ultra",
    imgPr:"https://m.media-amazon.com/images/I/7115gVwyHGL._AC_SL1500_.jpg",
    pricePr:6676,
    detailesPr:["6.9 Infinity-O display with Dynamic AMOLED technology guarantees detailed images with true-to-life colours.","12 GB of RAM and 256 GB of internal storage.","A powerful 4,500 mAh battery.","The S Pen with Bluetooth functionality, that lets you write, draw and control many important features using intuitive gestures."],
    typePr:"Electronics",
    ratingPr:71,
    brandPr:"SAMSUNG",
    quantity:3
},
{
    idPr:75,
    namePr:"Electric Meat Grinder",
    imgPr:"https://m.media-amazon.com/images/I/315xleVCNaL._AC_.jpg",
    pricePr:590,
    detailesPr:["powerful motor : 3000 watt","grinding 2100 grams per minute","Reverse Function","Full plastic body with stainless steel Tray"],
    typePr:"Kitchen",
    ratingPr:23,
    brandPr:"AlSaif",
    quantity:4
},
{
    idPr:76,
    namePr:"GUESS Women's New Vibe Shoulder Bag",
    imgPr:"https://images-eu.ssl-images-amazon.com/images/I/A1QXPPhfcIL._AC_SR462,693_.jpg",
    pricePr:251,
    detailesPr:["NEW VIBE CNVRTBLE ROUND CASE","100% COTTON","Zip ClosureType"],
    typePr:"Fashion",
    ratingPr:54,
    brandPr:"GUESS",
    quantity:7
},
{
    idPr:77,
    namePr:"Samsung Galaxy S21 Ultra 5G",
    imgPr:"https://m.media-amazon.com/images/I/61xU77XA2rS._AC_SL1000_.jpg",
    pricePr:4296,
    detailesPr:["PRO-GRADE CAMERA: Capture the never-been-seen before with two 10MP telephoto, 12MP ultra wide, 108MP wide, and 40MP front camera. Get closer without making a move with the Dual Tele Zoom system with 100x Space Zoom. It's a massive leap for mobile photography.","SHARP 8K VIDEO: Record in 8K, the highest resolution video in a smartphone, and get crisp footage that looks better than the cinema. And with 8K Video Snap, you can pull epic high-resolution photos straight from 8K video.","DYNAMIC AMOLED 2X DISPLAY: Content comes alive on the HDR10+ certified Infinity-O 6.8-inch screen with AMOLED 2X technology for the brightest and most vivid colors. Complementing it is a 120Hz refresh rate, so that you get incredibly smooth scrolling and gaming.","POWERFUL 5NM PROCESSOR: Galaxy's first 5NM processor packs power and speed in a smaller packagem offering you more efficiency and performance. Whether you’re gaming, streaming, shooting, or editing, you can be sure your phone will keep up with you.","ALL DAY INTELLIGENT BATTERY: Stay powered for the whole day with the 5000mAh with 25W Super Fast Charing and 15W Fast Wireless Charging 2.0. It doesn't stop there – the battery is intelligent, analysing your usage patterns to save more power, giving you more charge."],
    typePr:"Electronics",
    ratingPr:64,
    brandPr:"SAMSUNG",
    quantity:8
},
{
    idPr:78,
    namePr:"Artely Vip End Table, Freijo Brown with Off White",
    imgPr:"https://m.media-amazon.com/images/I/81cKszAdbzL._AC_SL1500_.jpg",
    pricePr:130,
    detailesPr:["Retro design: create a comfortable, charming and unique living room","Utility: ideal support to cups, mugs, cellphone, TV control and decorations","Versatility: may be used as an end table, sofa table and bedside table, always decorating and giving the final charm to the room","25 mm thickness feet: robustness, resistance and high quality","Quality: made from selected MDF and MDP (reconstituted wood) from reforested forests"],
    typePr:"Furniture",
    ratingPr:10,
    brandPr:"Artely",
    quantity:1
},
{
    idPr:79,
    namePr:"ASUS ZenBook Duo UX481",
    imgPr:"https://m.media-amazon.com/images/I/81PGX7kO4kL._AC_SL1500_.jpg",
    pricePr:7524,
    detailesPr:["ScreenPad Plus: 12.6 inch matte touchscreen, giving you endless way to optimize your multitasking experience by extending the screen or split windows and apps on both displays","14 inches Full HD NanoEdge touchscreen glossy main display","Latest 10th generation Intel Core i7 10510U Processor (8M Cache, up to 4.9 GHz)","Fast storage and memory featuring 512GB PCIe NVMe M.2 SSD with 8GB LPDDR3 RAM","Built-in IR camera for facial recognition sign in with Windows HelloExclusive ErgoLift design for improved typing position, optimized cooling system and enhanced audio performanceExtensive connectivity with Gig+ Wi-Fi 6 (802.11ax), HDMI, and USB Type C (USB Transfer speed may vary. Learn more on ASUS website)"],
    typePr:"Electronics",
    ratingPr:45,
    brandPr:"ASUS",
    quantity:1
},
{
    idPr:80,
    namePr:"Seiko SRPG13 Prospex Men's Watch Green",
    imgPr:"https://m.media-amazon.com/images/I/61LwlE7bRiL._AC_UX522_.jpg",
    pricePr:1823,
    detailesPr:["Stainless Steel Case","Polyester Band","Automatic With Manual Winding","20 Bar Water Resistance"],
    typePr:"Fashion",
    ratingPr:89,
    brandPr:"Seiko",
    quantity:5
}]